In [2]:
library(data.table)

In [3]:
mydir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/review_files/'

In [4]:
length(list.files(mydir,"cc.tsv"))
# list.files(mydir,"cc.tsv")

[1] 21

In [5]:
list.files(mydir,"schmiedel")

 [1] "schmiedel_1-s2.0-S009286741831331X-mmc3.xlsx"
 [2] "schmiedel_b_naive_QTD000474.cc.tsv.gz"
 [3] "schmiedel_cd14_mono_QTD000504.cc.tsv.gz"
 [4] "schmiedel_cd16_mono_QTD000499.cc.tsv.gz"
 [5] "schmiedel_cd4_naive_QTD000479.cc.tsv.gz"
 [6] "schmiedel_cd8_naive_QTD000489.cc.tsv.gz"
 [7] "schmiedel_nk_QTD000509.cc.tsv.gz"
 [8] "schmiedel_tfh_QTD000439.cc.tsv.gz"
 [9] "schmiedel_th1_17_QTD000459.cc.tsv.gz"
[10] "schmiedel_th1_QTD000449.cc.tsv.gz"
[11] "schmiedel_th17_QTD000444.cc.tsv.gz"
[12] "schmiedel_th2_QTD000454.cc.tsv.gz"
[13] "schmiedel_treg_mem_QTD000469.cc.tsv.gz"
[14] "schmiedel_treg_naive_QTD000464.cc.tsv.gz"

In [6]:
suppl_tables_dir = '/directflow/SCCGGroupShare/projects/anncuo/TenK10K_pilot/tenk10k/ms_tables/'
df_common_ct = as.data.frame(fread(paste0(suppl_tables_dir,'all_eqtls_fdr_5pct.tsv')))
head(df_common_ct)

  gene            ACAT_p       top_MarkerID                 top_pval
1 ENSG00000020633 5.782049e-04 1:24970252:A:C               1.42751e-05
2 ENSG00000049247 1.234790e-12 1:7913587:T:TTTTTTGTTGTTGTTG 6.48378e-15
3 ENSG00000116288 8.678405e-04 1:8065826:C:CT               8.38885e-06
4 ENSG00000117091 5.320189e-13 1:160705479:G:C              1.97810e-15
5 ENSG00000117394 1.212478e-05 1:42971584:CA:C              2.24877e-07
6 ENSG00000117632 5.598092e-09 1:25972262:A:AT              4.89130e-11
  qvalue       celltype ASDC_is_expressed B_intermediate_is_expressed
1 1.925410e-02 ASDC     TRUE               TRUE
2 2.927374e-10 ASDC     TRUE              FALSE
3 2.624051e-02 ASDC     TRUE               TRUE
4 1.280392e-10 ASDC     TRUE               TRUE
5 7.925513e-04 ASDC     TRUE               TRUE
6 7.800008e-07 ASDC     TRUE               TRUE
  B_memory_is_expressed B_naive_is_expressed ⋯ ILC_is_egene MAIT_is_egene
1  TRUE                  TRUE                ⋯ FALSE         TRUE
2 FALSE                 FALSE                ⋯  TRUE         TRUE
3  TRUE                  TRUE                ⋯ FALSE         TRUE
4  TRUE                  TRUE                ⋯ FALSE         TRUE
5  TRUE                  TRUE                ⋯ FALSE        FALSE
6  TRUE                  TRUE                ⋯ FALSE        FALSE
  NK_is_egene NK_CD56bright_is_egene NK_Proliferating_is_egene pDC_is_egene
1 TRUE        FALSE                  FALSE                     FALSE
2 TRUE         TRUE                   TRUE                     FALSE
3 TRUE         TRUE                   TRUE                      TRUE
4 TRUE         TRUE                   TRUE                      TRUE
5 TRUE        FALSE                  FALSE                     FALSE
6 TRUE        FALSE                  FALSE                      TRUE
  Plasmablast_is_egene Treg_is_egene n_celltypes_expressed n_celltypes_egene
1  TRUE                 TRUE         28                    14
2 FALSE                 TRUE         14                    14
3  TRUE                 TRUE         28                    26
4  TRUE                FALSE         28                    22
5 FALSE                FALSE         27                    10
6 FALSE                 TRUE         28                    15

In [7]:
# Classical monocytes (CD14+)

In [8]:
# TenK10K
df_mono_c = df_common_ct[df_common_ct$celltype == 'CD14_Mono',]
tenk10k_monocyte_c_egenes = unique(df_mono_c$gene)
length(tenk10k_monocyte_c_egenes)
length(unique(df_mono_c[df_mono_c$top_pval < 1e-6,]$gene))

[1] 9026

[1] 5468

In [9]:
# Schmiedel et al 
schmiedel_catalogue_file_mono_c = paste0(mydir,'schmiedel_cd14_mono_QTD000504.cc.tsv.gz')
schmiedel_df_mono_c <- read.csv(gzfile(schmiedel_catalogue_file_mono_c), sep="\t")
nrow(schmiedel_df_mono_c)
head(schmiedel_df_mono_c,2)

[1] 14610656

  molecular_trait_id chromosome position ref alt variant         ma_samples
1 ENSG00000160075    1          758351   A   G   chr1_758351_A_G 15
2 ENSG00000176022    1          758351   A   G   chr1_758351_A_G 15
  maf       pvalue   beta     se       type ac an  r2
1 0.0824176 0.429225 0.208164 0.261918 SNP  15 182 0.44118
2 0.0824176 0.511276 0.149917 0.227161 SNP  15 182 0.44118
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000160075           ENSG00000160075 65.170     rs12238997
2 ENSG00000176022           ENSG00000176022 13.192     rs12238997

In [10]:
length(unique(schmiedel_df_mono_c$molecular_trait_id))
length(unique(schmiedel_df_mono_c[schmiedel_df_mono_c$pvalue < 1e-6,'molecular_trait_id']))

[1] 1946

[1] 1941

In [22]:
schmiedel_egenes = unique(schmiedel_df_mono_c[schmiedel_df_mono_c$pvalue < 1e-6,'molecular_trait_id'])
length(schmiedel_egenes)
tenk10k_egenes = unique(df_mono_c[df_mono_c$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 1941

[1] 5468

[1] 1528

[1] 0.7872231

In [ ]:
# Non-classical monocytes (CD16+)

In [17]:
# TenK10K
df_mono_nc = df_common_ct[df_common_ct$celltype == 'CD16_Mono',]
tenk10k_monocyte_nc_egenes = unique(df_mono_nc$gene)
length(tenk10k_monocyte_nc_egenes)
length(unique(df_mono_nc[df_mono_nc$top_pval < 1e-6,]$gene))

[1] 7930

[1] 4691

In [18]:
# Schmiedel et al 
schmiedel_catalogue_file_mono_nc = paste0(mydir,'schmiedel_cd16_mono_QTD000499.cc.tsv.gz')
schmiedel_df_mono_nc <- read.csv(gzfile(schmiedel_catalogue_file_mono_nc), sep="\t")
nrow(schmiedel_df_mono_nc)
head(schmiedel_df_mono_nc,2)

[1] 15137200

  molecular_trait_id chromosome position ref alt variant         ma_samples
1 ENSG00000188976    1          758351   A   G   chr1_758351_A_G 15
2 ENSG00000189339    1          758351   A   G   chr1_758351_A_G 15
  maf       pvalue   beta      se       type ac an  r2
1 0.0833333 0.586364 -0.212464 0.388792 SNP  15 180 0.44118
2 0.0833333 0.372973  0.316674 0.353322 SNP  15 180 0.44118
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000188976           ENSG00000188976 51.678     rs12238997
2 ENSG00000189339           ENSG00000189339 22.530     rs12238997

In [19]:
length(unique(schmiedel_df_mono_nc$molecular_trait_id))
length(unique(schmiedel_df_mono_nc[schmiedel_df_mono_nc$pvalue < 1e-6,'molecular_trait_id']))

[1] 1922

[1] 1914

In [21]:
schmiedel_egenes = unique(schmiedel_df_mono_nc[schmiedel_df_mono_nc$pvalue < 1e-6,'molecular_trait_id'])
length(schmiedel_egenes)
tenk10k_egenes = unique(df_mono_nc[df_mono_nc$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 1914

[1] 4691

[1] 1454

[1] 0.7596656

In [ ]:
# B naive

In [23]:
# TenK10K
df_b_naive = df_common_ct[df_common_ct$celltype == 'B_naive',]
tenk10k_b_naive_egenes = unique(df_b_naive$gene)
length(tenk10k_b_naive_egenes)
length(unique(df_b_naive[df_b_naive$top_pval < 1e-6,]$gene))

[1] 9153

[1] 5791

In [25]:
# Schmiedel et al 
schmiedel_catalogue_file_b_naive = paste0(mydir,'schmiedel_b_naive_QTD000474.cc.tsv.gz')
schmiedel_df_b_naive <- read.csv(gzfile(schmiedel_catalogue_file_b_naive), sep="\t")
nrow(schmiedel_df_b_naive)
head(schmiedel_df_b_naive,2)

[1] 13624930

  molecular_trait_id chromosome position ref alt variant         ma_samples
1 ENSG00000107404    1          758351   A   G   chr1_758351_A_G 15
2 ENSG00000189339    1          758351   A   G   chr1_758351_A_G 15
  maf       pvalue   beta     se       type ac an  r2
1 0.0824176 0.650974 0.109122 0.240248 SNP  15 182 0.44118
2 0.0824176 0.772704 0.101521 0.350228 SNP  15 182 0.44118
  molecular_trait_object_id gene_id         median_tpm rsid
1 ENSG00000107404           ENSG00000107404  6.873     rs12238997
2 ENSG00000189339           ENSG00000189339 56.061     rs12238997

In [26]:
length(unique(schmiedel_df_b_naive$molecular_trait_id))
length(unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id']))

[1] 1826

[1] 1825

In [27]:
schmiedel_egenes = unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id'])
length(schmiedel_egenes)
tenk10k_egenes = unique(df_b_naive[df_b_naive$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 1825

[1] 5791

[1] 1335

[1] 0.7315068

In [ ]:
# NK

In [28]:
# TenK10K
df_nk = df_common_ct[df_common_ct$celltype == 'NK',]
tenk10k_nk_egenes = unique(df_nk$gene)
length(tenk10k_nk_egenes)
length(unique(df_nk[df_nk$top_pval < 1e-6,]$gene))

[1] 10839

[1] 7315

In [29]:
# Schmiedel et al 
schmiedel_catalogue_file_nk = paste0(mydir,'schmiedel_nk_QTD000509.cc.tsv.gz')
schmiedel_df_nk <- read.csv(gzfile(schmiedel_catalogue_file_nk), sep="\t")
nrow(schmiedel_df_nk)
length(unique(schmiedel_df_nk$molecular_trait_id))
length(unique(schmiedel_df_nk[schmiedel_df_nk$pvalue < 1e-6,'molecular_trait_id']))

[1] 12411338

[1] 1568

[1] 1566

In [30]:
schmiedel_egenes = unique(schmiedel_df_nk[schmiedel_df_nk$pvalue < 1e-6,'molecular_trait_id'])
length(schmiedel_egenes)
tenk10k_egenes = unique(df_nk[df_nk$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 1566

[1] 7315

[1] 1212

[1] 0.7739464

In [31]:
# CD4 naive

In [32]:
# TenK10K
df_cd4_naive = df_common_ct[df_common_ct$celltype == 'CD4_Naive',]
tenk10k_cd4_naive_egenes = unique(df_cd4_naive$gene)
length(tenk10k_cd4_naive_egenes)
length(unique(df_cd4_naive[df_cd4_naive$top_pval < 1e-6,]$gene))

[1] 10877

[1] 7356

In [33]:
# Schmiedel et al 
schmiedel_catalogue_file_cd4_naive = paste0(mydir,'schmiedel_cd4_naive_QTD000479.cc.tsv.gz')
schmiedel_df_cd4_naive <- read.csv(gzfile(schmiedel_catalogue_file_cd4_naive), sep="\t")
nrow(schmiedel_df_cd4_naive)
# head(schmiedel_df_cd4_naive)
length(unique(schmiedel_df_cd4_naive$molecular_trait_id))
length(unique(schmiedel_df_cd4_naive[schmiedel_df_cd4_naive$pvalue < 1e-6,'molecular_trait_id']))

[1] 16153237

[1] 2075

[1] 2067

In [34]:
schmiedel_egenes = unique(schmiedel_df_cd4_naive[schmiedel_df_cd4_naive$pvalue < 1e-6,'molecular_trait_id'])
length(schmiedel_egenes)
tenk10k_egenes = unique(df_cd4_naive[df_cd4_naive$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 2067

[1] 7356

[1] 1566

[1] 0.7576197

In [35]:
# CD8 naive

In [36]:
# TenK10K
df_cd8_naive = df_common_ct[df_common_ct$celltype == 'CD8_Naive',]
tenk10k_cd8_naive_egenes = unique(df_cd8_naive$gene)
length(tenk10k_cd8_naive_egenes)
length(unique(df_cd8_naive[df_cd8_naive$top_pval < 1e-6,]$gene))

[1] 8270

[1] 4856

In [37]:
# Schmiedel et al 
schmiedel_catalogue_file_cd8_naive = paste0(mydir,'schmiedel_cd8_naive_QTD000489.cc.tsv.gz')
schmiedel_df_cd8_naive <- read.csv(gzfile(schmiedel_catalogue_file_cd8_naive), sep="\t")
nrow(schmiedel_df_cd8_naive)
# head(schmiedel_df_cd8_naive)
length(unique(schmiedel_df_cd8_naive$molecular_trait_id))
length(unique(schmiedel_df_cd8_naive[schmiedel_df_cd8_naive$pvalue < 1e-6,'molecular_trait_id']))

[1] 17058620

[1] 2186

[1] 2177

In [38]:
schmiedel_egenes = unique(schmiedel_df_cd8_naive[schmiedel_df_cd8_naive$pvalue < 1e-6,'molecular_trait_id'])
length(schmiedel_egenes)
tenk10k_egenes = unique(df_cd8_naive[df_cd8_naive$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 2177

[1] 4856

[1] 1436

[1] 0.6596233

In [33]:
# T reg

In [39]:
# TenK10K
df_treg = df_common_ct[df_common_ct$celltype == 'Treg',]
tenk10k_treg_egenes = unique(df_treg$gene)
length(tenk10k_treg_egenes)
length(unique(df_treg[df_treg$top_pval < 1e-6,]$gene))

[1] 6071

[1] 3480

In [40]:
# Schmiedel et al 
schmiedel_catalogue_file_treg_mem = paste0(mydir,'schmiedel_treg_mem_QTD000469.cc.tsv.gz')
schmiedel_df_treg_mem <- read.csv(gzfile(schmiedel_catalogue_file_treg_mem), sep="\t")
treg_mem_egenes = unique(schmiedel_df_treg_mem[schmiedel_df_treg_mem$pvalue < 1e-6,'molecular_trait_id'])
schmiedel_catalogue_file_treg_naive = paste0(mydir,'schmiedel_treg_naive_QTD000464.cc.tsv.gz')
schmiedel_df_treg_naive <- read.csv(gzfile(schmiedel_catalogue_file_treg_naive), sep="\t")
treg_naive_egenes = unique(schmiedel_df_treg_naive[schmiedel_df_treg_naive$pvalue < 1e-6,'molecular_trait_id'])
length(unique(c(treg_mem_egenes,treg_naive_egenes)))

[1] 2548

In [41]:
schmiedel_egenes = unique(c(treg_mem_egenes,treg_naive_egenes))
length(schmiedel_egenes)
tenk10k_egenes = unique(df_treg[df_treg$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 2548

[1] 3480

[1] 1396

[1] 0.5478807

In [37]:
# CD4 mem

In [42]:
# TenK10K
df_cd4 = df_common_ct[df_common_ct$celltype %in% c('CD4_TCM','CD4_TEM'),]
tenk10k_cd4_egenes = unique(df_cd4$gene)
length(tenk10k_cd4_egenes)
length(unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene))

[1] 11848

[1] 7995

In [43]:
# Schmiedel et al 
schmiedel_catalogue_file_b_naive = paste0(mydir,'schmiedel_tfh_QTD000439.cc.tsv.gz')
schmiedel_df_b_naive <- read.csv(gzfile(schmiedel_catalogue_file_b_naive), sep="\t")
tfh_egenes = unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id'])
#
schmiedel_catalogue_file_b_naive = paste0(mydir,'schmiedel_th1_17_QTD000459.cc.tsv.gz')
schmiedel_df_b_naive <- read.csv(gzfile(schmiedel_catalogue_file_b_naive), sep="\t")
th1_17_egenes = unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id'])
#
schmiedel_catalogue_file_b_naive = paste0(mydir,'schmiedel_th1_QTD000449.cc.tsv.gz')
schmiedel_df_b_naive <- read.csv(gzfile(schmiedel_catalogue_file_b_naive), sep="\t")
th1_egenes = unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id'])
#
schmiedel_catalogue_file_b_naive = paste0(mydir,'schmiedel_th17_QTD000444.cc.tsv.gz')
schmiedel_df_b_naive <- read.csv(gzfile(schmiedel_catalogue_file_b_naive), sep="\t")
th17_egenes = unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id'])
#
schmiedel_catalogue_file_b_naive = paste0(mydir,'schmiedel_th2_QTD000454.cc.tsv.gz')
schmiedel_df_b_naive <- read.csv(gzfile(schmiedel_catalogue_file_b_naive), sep="\t")
th2_egenes = unique(schmiedel_df_b_naive[schmiedel_df_b_naive$pvalue < 1e-6,'molecular_trait_id'])
#
length(unique(c(tfh_egenes, th1_17_egenes, th1_egenes, th17_egenes, th2_egenes)))

[1] 3165

In [44]:
schmiedel_egenes = unique(c(tfh_egenes, th1_17_egenes, th1_egenes, th17_egenes, th2_egenes))
length(schmiedel_egenes)
tenk10k_egenes = unique(df_cd4[df_cd4$top_pval < 1e-6,]$gene)
length(tenk10k_egenes)
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])
length(schmiedel_egenes[schmiedel_egenes %in% tenk10k_egenes])/length(schmiedel_egenes)

[1] 3165

[1] 7995

[1] 2376

[1] 0.7507109